#!/bin/sh
rm -f tmp.config
echo "(load \"Compiler/config.sch\")" >> tmp.config
echo "(config " >> tmp.config
for i
do
	echo \"$i\" >> tmp.config
done
echo ")" >> tmp.config
echo "(exit)" >> tmp.config
scheme tmp.config
rm tmp.config

