.TH LARCENY 1 "16 April 1992"
.SH NAME
larceny \- IEEE/ANSI/R4RS Scheme System for the Sun4.
.SH SYNOPSIS
.LP
.B larceny 
[ options ] heapfile
.SH DESCRIPTION
.LP
Larceny accepts zero or more options and the name of a heap image file.
It reads the
heap image into memory and transfers control to the startup procedure in
the heap image, which in an interactive setting is the Scheme REP-loop.
However, users can dump heaps which have other start-up procedures,
thereby creating stand-alone applications.
.PP
Heaps come in two flavors, single and split. The single heap is loaded into
the tenured area before execution (although see the \-E option, below). Split
heaps are loaded partly into the static area and partly into the tenured
area (again, see the \-E option).
.SH OPTIONS
.TP 9
.B \-t nnnn
Tenured heap size in bytes (decimal). The tenured heap size currently defaults
to 1MB, which is too little in many cases.
.TP
.B \-e nnnn
Ephemeral heap size in bytes (decimal). The ephemeral heap defaults to 1MB.
.TP
.B \-l nnnn
Ephemeral watermark in bytes (decimal). The ephemeral watermark defaults to
50% of the ephemeral heap size (even in the presence of \-e).
.TP
.B \-s nnnn
Stack cache size in bytes (decimal). The default is 64KB.
.TP
.B \-I nnnn
The initial value of the timer. The default is 0xFFFFFFFF (i.e. -1). However,
the system won't accept a negative number as an argument here, so the best
you can do is 0x7FFFFFFF (and you have to write it all in decimal :-).
.TP
.B \-E
Load non-static part of heap into ephemeral area. The default is to load the
non-static part into the tenured area, and sometimes you don't want this to 
happen (although the situations where this is true are very obscure).
.TP
.B \-d
Raise the level of diagnostic output by one. It starts at 0; each \-d 
increments it by 1.
.TP
.B \-B
Stop at every breakpoint.
.TP
.B \-z
Turn on single-stepping. This assumes your code (or part of it) was
compiled with single-stepping enabled, although no harm results if it
wasn't, you just won't single step.
.TP
.B \-P
Print memory usage statistics after the heap has been loaded.
.TP
.B \-v
Do a vadvise( V_ANOM ) to tell the virtual memory system about random
paging behavior. Be warned that experience shows that doing this does
not help much and can in fact result in worse paging behavior.
.SH BUGS
There should be a way to give heap sizes in KB and/or MB.

The tenured heap should be automatically expanded on overflow.

A better way to give timer limit would be nice.

An argument could be made that the watermark should be given in percent of
the heap size rather than in bytes, although they are essentially equivalent.

Others, no doubt.

.SH VERSION
Version 0.14, very alpha.

.SH AUTHORS
Lars Thomas Hansen and Will Clinger.

.SH SEE ALSO
Revised^4 Report on Algorithmic Language Scheme
.sp 0
Larceny Notes
