.TH LARCENY 1 "31 July 1995"
.SH NAME
larceny \- IEEE/ANSI/R4RS Scheme System for the Sun4.
.SH SYNOPSIS
.LP
.B larceny 
[ options ] heapfile
.SH DESCRIPTION
.LP
Larceny accepts zero or more options and the name of a heap image file.
It reads the
heap image into memory and transfers control to the startup procedure in
the heap image, which in an interactive setting is the Scheme REP-loop.
However, users can dump heaps which have other start-up procedures,
thereby creating stand-alone applications.
.PP
Heaps come in two flavors, single and split. The single heap is loaded into
the tenured area before execution. Split
heaps are loaded partly into the static area and partly into the tenured
area.
.SH OPTIONS
.TP 9
.B \-tsize nnnn
Tenured heap size in bytes. The tenured heap size currently defaults
to 1MB, which is too little in many cases.
.TP
.B \-esize nnnn
Ephemeral heap size in bytes. The ephemeral heap defaults to 1MB.
.TP
.B \-rpool nnnn
Remembered set storage pool size in elements.
.TP
.B \-rhash nnnn
Remembered set hash table size in elements, a power of 2.
.TP
.B -ssb nnnn
Static storage buffer size in elements (words).
.TP
.B \-emark n
Ephemeral watermark in percent. The ephemeral watermark defaults to 50%.
.TP
.B \-thimark n
Tenured area high watermark in percent. Affects heap expansion. Defaults
to 75%.
.TP
.B \-tlomark n
Tenured area low watermark in percent. Affects heap contraction. Defaults
to 25%.
.TP
.B \-ticks nnnn
The initial value of the timer. The default is 0xFFFFFFFF. Timer interrupts
are not yet supported in Larceny, so if the timer expires you will receive
an error message and the system will abort. Will be fixed in v0.25.
.TP
.B \-break
Enable breakpoints.
.TP
.B \-step
Enable single-stepping. This assumes your code (or part of it) was
compiled with single-stepping enabled, although no harm results if it
wasn't, you just won't single step.
.TP 
.B \-timer
Disable timer interrupts at starup.
.TP
.B \-memstats
Print memory usage statistics after the heap has been loaded.
.TP 
.B \-quiet
Suppress all but the most urgent messages.
.TP
.B \-help
Print a help message.

.PP
Option values can be given in decimal (nnnn), hex (0xnnnn), octal
(0nnnn), or suffixed with K (for KB) or M (for MB) when that makes
sense.

.SH BUGS
There are plenty of buts in the program itself.

The manual page could be more helpful.

Most of the Larceny Notes are severely out of date.

.SH VERSION
Version 0.24, still very alpha.

.SH AUTHORS
Lars Thomas Hansen (most of the runtime) and William D. Clinger (the compiler
and parts of the runtime).

.SH SEE ALSO
Revised^4 Report on Algorithmic Language Scheme
.sp 0
Larceny Notes
