(!label "Overview" 3 "node_chap_1" "1")
(!label "Installation" 4 "node_chap_2" "2")
(!label "Supported Schemes" 4 "node_sec_2.1" "2.1")
(!label "Installing" 4 "node_sec_2.2" "2.2")
(!label "Chicken" 4 "node_sec_2.2.1" "2.2.1")
(!label "Scheme48" 4 "node_sec_2.2.2" "2.2.2")
(!label "Other Schemes" 4 "node_sec_2.2.3" "2.2.3")
(!label "Caveats" 4 "node_sec_2.2.4" "2.2.4")
(!label "Sassy and GNU Emacs" 4 "node_sec_2.3" "2.3")
(!label "Porting Sassy" 4 "node_sec_2.4" "2.4")
(!label "Usage" 5 "node_chap_3" "3")
(!label "Basic Syntax" 5 "node_sec_3.1" "3.1")
(!label "special-escape" 5 "node_tag_Temp_2" "{special escape form}")
(!label "escapes" 5 "node_tag_Temp_3" "{Escapes}")
(!label "escapes2" 5 "node_tag_Temp_4" "{escapes}")
(!label "Escaping to Scheme" 5 "node_sec_3.2" "3.2")
(!label "Directives" 6 "node_chap_4" "4")
(!label "directive" 6 "node_tag_Temp_5" "{directive}")
(!label "directives" 6 "node_tag_Temp_6" "{directives}")
(!label "Label Definitions and Lexical Scoping" 6 "node_sec_4.1" "4.1")
(!label "Defining Labels" 6 "node_sec_4.1.1" "4.1.1")
(!label "Lexical Scoping" 6 "node_sec_4.1.2" "4.1.2")
(!label "The {\\scm{align}} special form" 6 "node_sec_4.2" "4.2")
(!label "Descriptions of directives" 6 "node_sec_4.3" "4.3")
(!label "\\scm{heap}" 6 "node_sec_4.3.1" "4.3.1")
(!label "\\scm{data}" 6 "node_sec_4.3.2" "4.3.2")
(!label "\\scm{text}" 6 "node_sec_4.3.3" "4.3.3")
(!label "add-sources" 6 "node_tag_Temp_7" "{additional sources}")
(!label "\\scm{include}" 6 "node_sec_4.3.4" "4.3.4")
(!label "\\scm{import}" 6 "node_sec_4.3.5" "4.3.5")
(!label "\\scm{export}" 6 "node_sec_4.3.6" "4.3.6")
(!label "\\scm{entry}" 6 "node_sec_4.3.7" "4.3.7")
(!label "\\scm{org}" 6 "node_sec_4.3.8" "4.3.8")
(!label "\\scm{macro}" 6 "node_sec_4.3.10" "4.3.10")
(!label "\\scm{begin}" 6 "node_sec_4.3.11" "4.3.11")
(!label "The Text Section" 7 "node_chap_5" "5")
(!label "the-text-section" 7 "node_tag_Temp_8" "{The Text Section}")
(!label "text section here" 7 "node_tag_Temp_9" "{here}")
(!label "Instructions" 7 "node_sec_5.1" "5.1")
(!label "instruct1" 7 "node_tag_Temp_10" "{Instructions}")
(!label "Immediates" 7 "node_sec_5.1.1" "5.1.1")
(!label "Addressing" 7 "node_sec_5.1.2" "5.1.2")
(!label "Operand Sizes" 7 "node_sec_5.1.3" "5.1.3")
(!label "Jumps and Calls" 7 "node_sec_5.1.4" "5.1.4")
(!label "branch-prefix" 7 "node_tag_Temp_11" "{see below}")
(!label "Prefixes" 7 "node_sec_5.1.5" "5.1.5")
(!label "Assertions" 7 "node_sec_5.2" "5.2")
(!label "Control Primitives" 7 "node_sec_5.3" "5.3")
(!label "The COMFY core" 7 "node_sec_5.3.1" "5.3.1")
(!label "Sassy Extensions" 7 "node_sec_5.3.2" "5.3.2")
(!label "begin text" 7 "node_tag_Temp_12" "{additional semantics}")
(!label "A Note on Branch Optimization" 7 "node_sec_5.3.3" "5.3.3")
(!label "Custom Relocations" 8 "node_chap_6" "6")
(!label "custom-reloc" 8 "node_tag_Temp_13" "{Custom Relocations}")
(!label "gram-cust-reloc" 8 "node_tag_Temp_14" "{\\verb{<custom-relocation>}}")
(!label "Output" 9 "node_chap_7" "7")
(!label "output api" 9 "node_tag_Temp_15" "{Sassy's output API}")
(!label "Record-types" 9 "node_sec_7.1" "7.1")
(!label "\\var{sassy-output}" 9 "node_sec_7.1.1" "7.1.1")
(!label "\\var{sassy-symbol}" 9 "node_sec_7.1.2" "7.1.2")
(!label "\\var{sassy-reloc}" 9 "node_sec_7.1.3" "7.1.3")
(!label "sas-reloc" 9 "node_tag_Temp_16" "{here}")
(!label "Additional procedures for \\var{sassy-output}" 9 "node_sec_7.2" "7.2")
(!label "\\var{push-stacks}" 9 "node_sec_7.3" "7.3")
(!label "Utilities" 9 "node_sec_7.4" "7.4")
(!label "Output Modules" 10 "node_chap_8" "8")
(!label "output module" 10 "node_tag_Temp_17" "{output module}")
(!label "Flat Binaries" 10 "node_sec_8.1" "8.1")
(!label "ELF Output" 10 "node_sec_8.2" "8.2")
(!label "Macro Expansions" 11 "node_chap_A" "A")
(!label "appendix-a" 11 "node_tag_Temp_18" "{Appendix A}")
(!label "Comparisons" 11 "node_sec_A.0.1" "A.0.1")
(!label "More Control Primitives" 11 "node_sec_A.0.2" "A.0.2")
(!label "ELF helpers" 11 "node_sec_A.0.3" "A.0.3")
(!label "cps-macros" 11 "node_tag_Temp_19" "{here}")
(!label "Explicit Continuation Versions" 11 "node_sec_A.0.4" "A.0.4")
