# $Id$
# Compat/Makefile

default:

clean:

realclean:
	( cd Chez ; $(MAKE) realclean )
	( cd Larceny ; $(MAKE) realclean )
	( cd Gambit-C ; $(MAKE) realclean )
	( cd MIT ; $(MAKE) realclean )

# eof
