(#%require (only mzscheme version))
(#%require (only mzscheme regexp-match))
(#%require (only mzscheme require))
(#%require (only mzscheme read-byte))
(#%require (only mzscheme write-byte))
(#%require (only mzscheme void))
(#%require (only mzscheme open-input-string))
(#%require (only mzscheme open-output-string))
(#%require (only mzscheme get-output-string))
(#%require (only mzscheme namespace-require/copy))
(#%require (only mzscheme make-namespace))
(#%require (only mzscheme file-or-directory-modify-seconds))
(#%require (only mzscheme current-directory))
(#%require (only mzscheme path->string))
(#%require (only mzscheme read-case-sensitive))
(#%require (only mzscheme bitwise-ior))
(#%require (only mzscheme bitwise-and))
(#%require (only mzscheme bitwise-xor))
(#%require (only mzscheme bitwise-not))
(#%require (only mzscheme arithmetic-shift))
(#%require (only mzscheme print-vector-length))
(#%require (only mzscheme file-exists?))
(#%require (only mzscheme port?))
(#%require (only mzscheme format))
(#%require (only mzscheme string->uninterned-symbol))
(#%require (only mzscheme getenv))
(#%require (only mzscheme system-type))
(#%require (only mzscheme sub1))
(#%require (only mzscheme with-handlers))
(#%require (only mzscheme bytes->list))
(#%require (only mzscheme real->floating-point-bytes))
(#%require (only mzscheme write-string))

(load (param-filename 'compatibility ".." "MzScheme" "compat.sch"))

