; -*- Scheme -*-
;
; Load the heap with the Scheme 313 compiler

(display "Building development system...") (newline) (newline)

(set! *optimize-level* 1)
(display "Chez Scheme v3.0 patch...") (newline)
(load "../Chez/sparcasm.patch")
(display "Chez Scheme/MacScheme compatibility package...") (newline)
(load "../Chez/compat.ss")
(display "Compiler proper...") (newline)
(load "sets.sch")
(load "pass1.imp.sch")
(load "pass1.aux.sch")
(load "pass1.sch")
(load "pass2.aux.sch")
(load "pass2.sch")
(load "pass3.sch")
(load "pass4.imp.sch")
(load "pass4.aux.sch")
(load "pass4p1.sch")
(load "pass4p2.sch")
(display "generic assembler...") (newline)
(load "assembler.scm")
(display "sparc assembler and code generator...") (newline)
(load "../Sparc/asm.sparc.scm")
(load "../Sparc/gen-primops.scm")
(display "sparc disassembler...") (newline)
(load "../Sparc/disasm.sparc.scm")
(display "bootstrap heap dumper...") (newline)
(load "dumpheap.scm")
(display "Compiler driver...") (newline)
(load "compile313.sch")
(load "../makeheap.scm")
(load "printlap.sch")
(set! listify? #f)
(display "Listing is off") (newline)
(newline)
