; Program to print .LAP files in some readable manner.
;
; $Id: printlap.sch,v 1.1 91/09/20 16:52:18 lth Exp Locker: lth $

(define readify-lap
  (let ((ilist `((,$.linearize .linearize)
		 (,$.label     .label)
		 (,$.proc      .proc)
		 (,$.cont      .cont)
		 (,$.align     .align)
		 (,$op1        op1)
		 (,$op2        op2)
		 (,$op3        op3)
		 (,$op2imm     op2imm)
		 (,$const      const)
		 (,$global     global)
		 (,$setglbl    setglbl)
		 (,$lexical    lexical)
		 (,$setlex     setlex)
		 (,$stack      stack)
		 (,$setstk     setstk)
		 (,$load       load)
		 (,$store      store)
		 (,$reg        reg)
		 (,$setreg     setreg)
		 (,$movereg    movereg)
		 (,$lambda     lambda)
		 (,$lexes      lexes)
		 (,$args=      args=)
		 (,$args>=     args>=)
		 (,$invoke     invoke)
		 (,$save       save)
		 (,$setrtn     setrtn)
		 (,$restore    restore)
		 (,$pop        pop)
		 (,$return     return)
		 (,$mvrtn      mvrtn)
		 (,$apply      apply)
		 (,$nop        nop)
		 (,$jump       jump)
		 (,$skip       skip)
		 (,$branch     branch)
		 (,$branchf    branchf)
		 (,$optb2      optb2)
		 (,$optb3      optb3))))

    (lambda (code)
      (map
        (lambda (x)
	  (let ((iname (cadr (assv (car x) ilist))))
	    (if (not (= (car x) $lambda))
		(cons iname (cdr x))
		(list iname (readify-lap (cadr x)) (caddr x)))))
	code))))
