# $Id$
# Experimental/Makefile

default:

# Solaris, at least
#unix-support.so:
#	gcc -fPIC -shared unix-support.c -lsocket -lnsl -o unix-support.so

# Linux
unix-support.so:
	gcc -fPIC -shared unix-support.c -lnsl -o unix-support.so

# eof
