@REM  Assemble the CommonLarceny heap
@REM
@SETLOCAL
@PUSHD %~d0%~p0
@CD ..\..

@REM  Build the debug version
ilasm.exe /QUIET /DEBUG=OPT /ALIGNMENT=4096 /OUTPUT:bin\Debug\CommonLarceny.exe dotnet.heap.asm-il Lib\Common\malcode.code-il Lib\Common\typetags.code-il Lib\Common\syscall-id.code-il Lib\Common\sys-win32.code-il Lib\Common\system-interface.code-il Lib\Common\error0.code-il Lib\IL\primops.code-il Lib\Common\sysparam.code-il Lib\Common\struct.code-il Lib\Common\command-line.code-il Lib\Common\list.code-il Lib\Common\vector.code-il Lib\Common\string.code-il Lib\Common\control.code-il Lib\Common\hash.code-il Lib\Common\hashtable.code-il Lib\Common\preds.code-il Lib\Common\oblist.code-il Lib\Common\mcode.code-il Lib\Common\memstats.code-il Lib\Common\ecodes.code-il Lib\Common\ehandler.code-il Lib\Common\error.code-il Lib\Common\timer.code-il Lib\Common\exit.code-il Lib\Common\dump.code-il Lib\Common\secret.code-il Lib\Common\iosys.code-il Lib\Common\fileio.code-il Lib\Common\conio.code-il Lib\Common\stringio.code-il Lib\Common\stdio.code-il Lib\Common\print.code-il Lib\Common\ioboot.code-il Lib\Common\format.code-il Lib\Common\sort.code-il Lib\Common\number.code-il Lib\Common\globals.code-il Lib\Common\profile.code-il Lib\Common\bignums-el.code-il Lib\Common\bignums.code-il Lib\Common\ratnums.code-il Lib\Common\rectnums.code-il Lib\Common\flonums-el.code-il Lib\Common\flonums.code-il Lib\Common\contag.code-il Lib\Common\num2str.code-il Lib\Common\belle.code-il Lib\Common\str2num.code-il Lib\Common\javadot-symbol.code-il Lib\Common\javadot-syntax.code-il Lib\Common\reader.code-il Lib\Common\env.code-il Lib\Common\procinfo.code-il Lib\Common\load.code-il Lib\Common\eval.code-il Lib\Common\syshooks.code-il Lib\Common\gcctl.code-il Lib\Common\toplevel.code-il Lib\IL\toplevel-target.code-il Lib\IL\loadable.code-il Lib\Common\go.code-il Repl\main.code-il Repl\reploop.code-il Interpreter\interp.code-il Interpreter\interp-prim.code-il Interpreter\switches.code-il Compiler\pass1.code-il Compiler\pass1.aux.code-il Compiler\pass2.aux.code-il Compiler\prefs.code-il Compiler\syntaxenv.code-il Compiler\syntaxrules.code-il Compiler\lowlevel.code-il Compiler\expand.code-il Compiler\usual.code-il Interpreter\macro-expand.code-il Lib\MzScheme\init.code-il Lib\MzScheme\wcm0.code-il Lib\MzScheme\wcm.code-il Lib\MzScheme\hash-compat.code-il Lib\MzScheme\misc.code-il Lib\MzScheme\record.code-il Lib\MzScheme\inspector.code-il Lib\MzScheme\struct-proc0.code-il Lib\MzScheme\struct-proc.code-il Lib\MzScheme\struct.code-il Lib\MzScheme\struct-macros.code-il Lib\MzScheme\instance0.code-il Lib\MzScheme\instance.code-il Lib\MzScheme\class.code-il Lib\MzScheme\generic.code-il Lib\MzScheme\gprint.code-il Lib\MzScheme\dotnet-ffi.code-il Lib\MzScheme\dotnet.code-il Lib\MzScheme\envaux.code-il Lib\MzScheme\compress.code-il Lib\MzScheme\identifier.code-il

@REM  Build the Release version
ilasm.exe /QUIET /OPTIMIZE /FOLD /CLOCK /ALIGNMENT=4096 /OUTPUT:bin\Release\CommonLarceny.exe dotnet.heap.asm-il Lib\Common\malcode.code-il Lib\Common\typetags.code-il Lib\Common\syscall-id.code-il Lib\Common\sys-win32.code-il Lib\Common\system-interface.code-il Lib\Common\error0.code-il Lib\IL\primops.code-il Lib\Common\sysparam.code-il Lib\Common\struct.code-il Lib\Common\command-line.code-il Lib\Common\list.code-il Lib\Common\vector.code-il Lib\Common\string.code-il Lib\Common\control.code-il Lib\Common\hash.code-il Lib\Common\hashtable.code-il Lib\Common\preds.code-il Lib\Common\oblist.code-il Lib\Common\mcode.code-il Lib\Common\memstats.code-il Lib\Common\ecodes.code-il Lib\Common\ehandler.code-il Lib\Common\error.code-il Lib\Common\timer.code-il Lib\Common\exit.code-il Lib\Common\dump.code-il Lib\Common\secret.code-il Lib\Common\iosys.code-il Lib\Common\fileio.code-il Lib\Common\conio.code-il Lib\Common\stringio.code-il Lib\Common\stdio.code-il Lib\Common\print.code-il Lib\Common\ioboot.code-il Lib\Common\format.code-il Lib\Common\sort.code-il Lib\Common\number.code-il Lib\Common\globals.code-il Lib\Common\profile.code-il Lib\Common\bignums-el.code-il Lib\Common\bignums.code-il Lib\Common\ratnums.code-il Lib\Common\rectnums.code-il Lib\Common\flonums-el.code-il Lib\Common\flonums.code-il Lib\Common\contag.code-il Lib\Common\num2str.code-il Lib\Common\belle.code-il Lib\Common\str2num.code-il Lib\Common\javadot-symbol.code-il Lib\Common\javadot-syntax.code-il Lib\Common\reader.code-il Lib\Common\env.code-il Lib\Common\procinfo.code-il Lib\Common\load.code-il Lib\Common\eval.code-il Lib\Common\syshooks.code-il Lib\Common\gcctl.code-il Lib\Common\toplevel.code-il Lib\IL\toplevel-target.code-il Lib\IL\loadable.code-il Lib\Common\go.code-il Repl\main.code-il Repl\reploop.code-il Interpreter\interp.code-il Interpreter\interp-prim.code-il Interpreter\switches.code-il Compiler\pass1.code-il Compiler\pass1.aux.code-il Compiler\pass2.aux.code-il Compiler\prefs.code-il Compiler\syntaxenv.code-il Compiler\syntaxrules.code-il Compiler\lowlevel.code-il Compiler\expand.code-il Compiler\usual.code-il Interpreter\macro-expand.code-il Lib\MzScheme\init.code-il Lib\MzScheme\wcm0.code-il Lib\MzScheme\wcm.code-il Lib\MzScheme\hash-compat.code-il Lib\MzScheme\misc.code-il Lib\MzScheme\record.code-il Lib\MzScheme\inspector.code-il Lib\MzScheme\struct-proc0.code-il Lib\MzScheme\struct-proc.code-il Lib\MzScheme\struct.code-il Lib\MzScheme\struct-macros.code-il Lib\MzScheme\instance0.code-il Lib\MzScheme\instance.code-il Lib\MzScheme\class.code-il Lib\MzScheme\generic.code-il Lib\MzScheme\gprint.code-il Lib\MzScheme\dotnet-ffi.code-il Lib\MzScheme\dotnet.code-il Lib\MzScheme\envaux.code-il Lib\MzScheme\compress.code-il Lib\MzScheme\identifier.code-il

@popd
@ENDLOCAL

