(define (reloadil)
  (load (make-filename *larceny-root* "Asm" "IL" "il.imp.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "il.imp2.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "config.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "util.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "il-gen.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "il-rtif.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "pass5p2.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "pass5p2-instructions.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "pass5p2-ops.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "pass5p2-listify.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "peepopt.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "il-src2string.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "il-sourcefile.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "dumpheap-il.sch"))
  (load (make-filename *larceny-root* "Asm" "IL" "dumpheap-extra.sch")))

(reloadil)
(peephole-optimization #f)
