# $Id$
# Lib/Makefile

default:

clean realclean:
	rm -f Sparc/*.lap Sparc/*.lop Sparc/*.c Sparc/*.o Sparc/*.seed \
		Sparc/*.fasl
	rm -f Standard-C/*.lap Standard-C/*.lop Standard-C/*.c \
		Standard-C/*.asm \
		Standard-C/*.o Standard-C/*.seed Standard-C/*.fasl
	rm -f Common/*.lap Common/*.lop Common/*.c Common/*.o Common/*.seed \
		Common/*.asm Common/*.fasl
	rm -f *.lap *.lop *.c *.asm *.o *.seed *.fasl
	rm -f Common/ecodes.sch Common/globals.sch

# eof
