; Copyright 1998 Lars T Hansen.
;
; $Id$
;
; Larceny development system -- makefile for compiling Scheme files.
;
; Procedures to call:
;  make-larceny-heap
;  make-larceny-eheap
;  make-petit-heap
;  make-auxlib
;  make-compat
;  make-compiler
;  make-sparcasm
;  make-petitasm
;  make-development-environment
;     makes auxlib, compat, compiler, sparcasm, petit-asm
;  make-gc-testsuite
;  make-regression-test

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Action procedures for the rules.

(define (make-compile target deps) 
  (display "Compiling ") (display target) (newline)
  (compile313 (car deps) target))

(define (make-assemble target deps)
  (display "Assembling ") (display target) (newline)
  (assemble313 (car deps) target))

(define (make-compile-file target deps)
  (display "Making ") (display target) (newline)
  (compile-file (car deps)))

(define (make-assemble-file target deps)
  (display "Making ") (display target) (newline)
  (assemble-file (car deps)))

(define (make-dumpheap target files)
  (display "Dumping ") (display target) (newline)
  (delete-file target)
  (let ((fn (string-append target ".map")))
    (delete-file fn)
    (call-with-output-file fn
      (lambda (p)
	(let ((q (apply build-heap-image target files)))
	  (pretty-print q p))))))  ; could be `display' or `write'.

(define (make-copy target src)
  (display "Copying ") (display target) (newline)
  (call-with-input-file (car src)
    (lambda (inp)
      (delete-file target)
      (call-with-output-file target
	(lambda (outp)
	  (let loop ((item (read-char inp)))
	    (if (eof-object? item)
		#t
		(begin (write-char item outp)
		       (loop (read-char inp))))))))))

(define objects
  (lambda (path ext files)
    (map (lambda (n) (string-append path n ext)) files)))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Projects for building the basic heap images.

; These are the base names of all the files that make up the basic heap.

(define heap-files 
  '(
    ; Fundamental

    "malcode"           ; really basic things
    "typetags"          ; type tags
    "unix"              ; OS primitives for Unix; $$trace procedure.
    "error0"            ; Boot-time 'error' procedure.
    "primops"           ; primop procedures

    ; General library

    "sysparam"		; system parameters
    "struct"            ; structures
    "argv"              ; command line arguments
    "list"              ; list procedures
    "vector"            ; vector procedures
    "string"            ; string and bytevector procs
    "control"           ; control procedures
    "preds"             ; some predicates
    "oblist"            ; symbol table
    "mcode"             ; millicode support
    "memstats"          ; runtime stats
    "ecodes"            ; exception codes
    "ehandler"          ; exception handler
    "error"             ; error/reset system
    "timer"             ; timer interrupts
    "exit"              ; exit procedure; exit/init hooks
    "dump"              ; dump-heap procedure
    "secret"            ; some "hidden" top-level names

    ; New I/O subsystem

    "iosys"             ; basic system
    "fileio"            ; file ports
    "conio"             ; console ports, i.e., terminal
    "stringio"          ; string ports
    "stdio"             ; user-level procedures
    "print"             ; write/display
    "ioboot"            ; one-time initialization

    "format"            ; `format' procedure.
    "number"            ; arithmetic
    "globals"           ; `global' offsets (for memstats)

    ; It's important for bellerophon to be loaded as late as possible
    ; because it depends on much of the rest of the system.

    "profile"           ; Profiling code
    "bignums"           ; Bignum support
    "ratnums"           ; Ratnum support
    "rectnums"          ; Rectnum support
    "flonums"           ; Flonum support
    "contag"            ; Contagion
    "num2str"           ; Number printer
    "belle"             ; Algorithm bellerophon
    "str2num"           ; Number parser
    "reader"            ; Reader
    "env"               ; R5RS environments
    "procinfo"          ; Heuristic procedure information
    "load"              ; Loader
    "syshooks"          ; System functions
    "gcctl"             ; Garbage collector policy control
    "go"                ; Driver

    ))

; Files in the bootstrap evaluator, repl, and toplevel env.

(define eval-files
  '("Repl/reploop"      ; Read-eval-print loop
    "Eval/eval"         ; Simple eval procedure (interpreter)
    "Eval/evalprim"     ; Primitives for interpreter
    "Eval/toplevel"     ; Top-level environment
    "Eval/macro-expand" ; Macro expander (for Eval)
    ))

; Files that hold system constants.

(define build-files
  '("Build/except.sh"   ; Exception codes (autogenerated)
    "Build/globals.sh"  ; Global values (autogenerated)
    ))

(define heap-project (make:new-project "larceny.heap"))

(make:rule heap-project ".lop" ".mal" make-assemble)
(make:rule heap-project ".lop" ".lap" make-assemble)
(make:rule heap-project ".lap" ".sch" make-compile)
(make:rule heap-project ".sch" ".sh" make-copy)
(make:deps heap-project '("larceny.heap") (objects "Lib/" ".lop" heap-files))
(make:deps heap-project '("larceny.heap") (objects "" ".lop" eval-files))
(make:deps heap-project '("Lib/globals.sch") '("Build/globals.sh"))
(make:deps heap-project '("Lib/ecodes.sch") '("Build/except.sh"))
(make:targets heap-project '("larceny.heap") make-dumpheap)

(define eheap-project (make:new-project "larceny.eheap"))

(make:rule eheap-project ".elop" ".mal" make-assemble)
(make:rule eheap-project ".elop" ".lap" make-assemble)
(make:rule eheap-project ".lap" ".sch" make-compile)
(make:rule eheap-project ".sch" ".sh" make-copy)
(make:deps eheap-project '("larceny.eheap")
	   (objects "Lib/" ".elop" heap-files))
(make:deps eheap-project '("larceny.eheap") (objects "" ".elop" eval-files))
(make:deps eheap-project '("Lib/globals.sch") '("Build/globals.sh"))
(make:deps eheap-project '("Lib/ecodes.sch") '("Build/except.sh"))
(make:targets eheap-project '("larceny.eheap") make-dumpheap)

(define petit-project (make:new-project "petit.heap"))

(make:rule petit-project ".lop" ".mal" make-assemble)
(make:rule petit-project ".lop" ".lap" make-assemble)
(make:rule petit-project ".lap" ".sch" make-compile)
(make:rule petit-project ".sch" ".sh" make-copy)
(make:deps petit-project '("petit.heap") (objects "Lib/" ".lop" heap-files))
(make:deps petit-project '("petit.heap") (objects "" ".lop" eval-files))
(make:deps petit-project '("Lib/globals.sch") '("Build/globals.sh"))
(make:deps petit-project '("Lib/ecodes.sch") '("Build/except.sh"))
(make:targets petit-project '("petit.heap") make-dumpheap)

; FIXME: The optional target name does not yet work.

(define (make-larceny-heap . rest)
  (if (not (write-barrier))
      (begin (write-barrier #t)
	     (display "NOTE: Turning on write barrier.")
	     (newline)))
  (cond ((null? rest)
	 (make:pretend #f)
	 (make:make heap-project "larceny.heap"))
	((string? (car rest))
	 (make:pretend #f)
	 (make:make heap-project (car rest)))
	(else
	 (make:pretend #t)
	 (make:make heap-project "larceny.heap"))))

(define (make-larceny-eheap . rest)
  (if (write-barrier)
      (begin (write-barrier #f)
	     (display "NOTE: Turning off write barrier.")
	     (newline)))
  (make:pretend (not (null? rest)))
  (make:make eheap-project "larceny.eheap"))

(define (make-petit-heap . rest)
  (make:pretend (not (null? rest)))
  (make:make petit-project "petit.heap"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Project for building all the files in the Compiler subdirectory.

(define compiler-project (make:new-project "compiler.date"))
(define compiler-files '("compile313" "help" "copy" "pass1.aux" "pass1" 
			 "pass2.aux" "pass2p1" "pass2p2" "pass4.aux"
			 "pass4p1" "pass4p2" "pass4p3" 
			 "sets" "switches" "sparc.imp" "patch0"
			 "printlap"))

(define comp-asm-files '("makefasl" "makefasl2" "dumpheap"))
(define comp-util-files '("make" "make-support" "init-comp"))


(make:rule compiler-project ".fasl" ".sch" make-compile-file)
(make:deps compiler-project '("compiler.date") 
	   (objects "Compiler/" ".fasl" compiler-files))
(make:deps compiler-project '("compiler.date")
	   (objects "Asm/Common/" ".fasl" comp-asm-files))
(make:deps compiler-project '("compiler.date") 
	   (objects "Util/" ".fasl" comp-util-files))
(make:targets compiler-project '("compiler.date") (lambda args #t))

(define (make-compiler . rest)
  (make:pretend (not (null? rest)))
  (make:make compiler-project "compiler.date"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Project for building all the files of the old SPARC assembler 
; (Asm/Sparc-old/*).

(define sparc-oldasm-project (make:new-project "sparc-oldasm.date"))
(define sparc-oldasm-files '("asmutil" "gen-msi" "gen-prim" "sparcasm" 
			     "sparcdis" "switches" "assembler" "peepopt"))

(make:rule sparc-oldasm-project ".fasl" ".sch" make-compile-file)
(make:deps sparc-oldasm-project '("sparc-oldasm.date")
	   (objects "Asm/Sparc-old/" ".fasl" sparc-oldasm-files))
(make:targets sparc-oldasm-project '("sparc-oldasm.date") (lambda args #t))

(define (make-sparc-oldasm . rest)
  (make:pretend (not (null? rest)))
  (make:make sparc-oldasm-project "sparc-oldasm.date"))



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Project for building all the files in the new generic assembler and
; the Sparc assembler.

(define sparcasm-project (make:new-project "sparcasm.date"))

(define generic-asm-files
  '("pass5p1" "asmutil" "asmutil32" "asmutil32be" "asmutil32le" "link-lop"))

(define sparcasm-files
  '("pass5p2" "gen-msi" "sparcprim-part1" "sparcprim-part2" "sparcprim-part3"
    "sparcasm" "sparcutil" "switches" "sparcdis" "peepopt"))

(make:rule sparcasm-project ".fasl" ".sch" make-compile-file)
(make:deps sparcasm-project '("sparcasm.date")
	   (objects "Asm/Common/" ".fasl" generic-asm-files))
(make:deps sparcasm-project '("sparcasm.date")
	   (objects "Asm/Sparc/" ".fasl" sparcasm-files))
(make:targets sparcasm-project '("sparcasm.date") (lambda args #t))

(define (make-sparcasm . rest)
  (make:pretend (not (null? rest)))
  (make:make sparcasm-project "sparcasm.date"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Project for building all the files in the standard-C assembler.

(define petit-asm-project (make:new-project "petitasm.date"))

(define petit-asm-files
  '("pass5p2" "switches" "dumpheap-extra"))

(make:rule petit-asm-project ".fasl" ".sch" make-compile-file)
(make:deps petit-asm-project '("petitasm.date")
	   (objects "Asm/Standard-C/" ".fasl" petit-asm-files))
(make:targets petit-asm-project '("petitasm.date") (lambda args #t))

(define (make-petit-asm . rest)
  (make:pretend (not (null? rest)))
  (make:make petit-asm-project "petitasm.date"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Project for building the Larceny compatibility files.

(define compat-project (make:new-project "Compat"))

(make:rule compat-project ".fasl" ".sch" make-compile-file)
(make:deps compat-project '("compat.date") '("Compat/Larceny/compat2.fasl"))
(make:targets compat-project '("compat.date") (lambda args #t))

(define (make-compat . rest)
  (make:pretend (not (null? rest)))
  (make:make compat-project "compat.date"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Project for building the Auxiliary libraries.

(define auxlib-project (make:new-project "Auxlib"))
(define auxlib-files '("misc" "list" "vector" "string" "sort" "pp" "io"))
(define experimental-files '("applyhook" "apropos" "system-stuff"))
(define debugger-files '("debug" "countcalls" "trace"))

(make:rule auxlib-project ".fasl" ".sch" make-compile-file)
(make:rule auxlib-project ".fasl" ".mal" make-assemble-file)
(make:deps auxlib-project '("auxlib.date")
	   (objects "Auxlib/" ".fasl" auxlib-files))
(make:deps auxlib-project '("auxlib.date")
	   (objects "Experimental/" ".fasl" experimental-files))
(make:deps auxlib-project '("auxlib.date")
	   '("Experimental/applyhook0.fasl"))
(make:deps auxlib-project '("auxlib.date")
	   (objects "Debugger/" ".fasl" debugger-files))
(make:targets auxlib-project '("auxlib.date") (lambda args #t))

(define (make-auxlib . rest)
  (make:pretend (not (null? rest)))
  (make:make auxlib-project "auxlib.date"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Project for building the GC test suite.

(define gc-testsuite-project (make:new-project "GC Testsuite"))
(define gc-testsuite-files
  '("dynamic" "gcbench0" "gcbench1" "grow" "lattice" "nbody"
	      "nboyer" "nucleic2" "permsort" "sboyer" "dummy"))

(make:rule gc-testsuite-project ".fasl" ".sch" make-compile-file)
(make:deps gc-testsuite-project '("gc-testsuite.date")
	   (objects "Testsuite/GC/" ".fasl" gc-testsuite-files))
(make:targets gc-testsuite-project '("gc-testsuite.date") (lambda args #t))

(define (make-gc-testsuite . rest)
  (make:pretend (not (null? rest)))
  (make:make gc-testsuite-project "gc-testsuite.date"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Regression tests.

(define regression-test-project
  (make:new-project "Regression tests"))

(define regression-test-files
  '("test" "fib" "ctak" "number" "char" "bool"))

(make:rule regression-test-project ".fasl" ".sch" make-compile-file)
(make:deps regression-test-project '("regression-test.date")
	   (objects "Testsuite/Lib/" ".fasl" regression-test-files))
(make:targets regression-test-project '("regression-test.date")
	      (lambda args #t))

(define (make-regression-test . rest)
  (make:pretend (not (null? rest)))
  (make:make regression-test-project "regression-test.date"))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Rebuild the entire development system, for all targets.

(define (make-development-environment . rest)
  (apply make-auxlib rest)
  (apply make-compiler rest)
  (apply make-sparcasm rest)
  (apply make-petit-asm rest)
  (apply make-compat rest)
  (compile-file "Lib/makefile.sch"))


; eof

