(
(loop foo)
(loope foo cx)
(loopz foo ecx)
(loopne foo)
(loopnz foo cx)
(jcxz foo)
(jecxz foo)
(call (dword 0))
(call (word 0))
(call 1000 (dword 1000))
(call 1000 (word 1000))
(call 1000 (dword 1000))
(call 1000 (word 1000))
(call far (dword (& ecx)))
(call far (word (& ecx)))
(call ecx)
(call (dword (& ecx)))
(call cx)
(call (word (& ecx)))
(jmp (dword 0))
(jmp near (dword 0))
(jmp (word 0))
(jmp near (word 0))
(jmp 1000 (dword 1000))
(jmp 1000 (word 1000))
(jmp 1000 (dword foo))
(jmp 1000 (word foo))
(jmp far (dword (& ecx)))
(jmp far (word (& ecx)))
(jmp ecx)
(jmp (dword (& ecx)))
(jmp cx)
(jmp (word (& ecx)))
)
