(
(rcl ebp 1)
(rcr (dword (& eax 1000)) 1)
(rol ebp cl)
(ror (dword (& eax 1000)) cl)
(sal ebp 9)
(sar (dword (& eax 1000)) (byte 9))
(shl dh  1)
(shr (byte (& ecx ebx))  1)
(rcl dh  cl)
(rcr (byte (& ecx ebx))  cl)
(rol dh  9)
(ror (byte (& ecx ebx))  9)
(sal bx 1) 
(sar (word (& 1000)) 1)
(shl bx cl)
(shr (word (& 1000)) cl)
(rcl bx 9)
(rcr (word (& 1000)) 9)
)
