#!/bin/sh
#
# Rts/expand-mac
# Larceny -- script to create .c files from macro (.mac) files
#
# $Id: expand-mac,v 1.1.1.1 1998/11/19 21:51:37 lth Exp $
#
# Usage: expand-mac input-file

# Chez Scheme host
SCHEME=scheme
ARGS=
GRUB='| tail +4'
HOST=chez

# Larceny host
# The heap file name must be the *absolute* path name of the heap file,
# and if the larceny executable is not in your path, then you must 
# use the absolute path name here too.
#HEAP=/proj/will/lth/larceny/bin/larceny.heap
#SCHEME="/proj/will/lth/larceny/bin/larceny $HEAP"
#ARGS=-args
#GRUB='| tail +1'
#HOST=larceny

if [ $# -ne 1 ]; then
  echo "usage: expand-mac filename"
  exit 1
fi
rm -f tmp.expand
echo "(load \"../Util/expander.sch\")" >> tmp.expand
echo "(expand-file \"$1\" \"`dirname $1`/`basename $1 .mac`.c\")" >> tmp.expand
echo "(exit)" >> tmp.expand
eval $SCHEME $ARGS tmp.expand $GRUB
rm tmp.expand
