#! /usr/bin/env bash

LARCENY=${LARCENY:-"../../../larceny"}


echo srfi-1-test; ${LARCENY} --r6rs --program srfi-1-test.sps; echo
echo srfi-2-test; ${LARCENY} --r6rs --program srfi-2-test.sps; echo
echo srfi-5-test; ${LARCENY} --r6rs --program srfi-5-test.sps; echo
echo srfi-6-test; ${LARCENY} --r6rs --program srfi-6-test.sps; echo
echo srfi-8-test; ${LARCENY} --r6rs --program srfi-8-test.sps; echo
echo srfi-9-test; ${LARCENY} --r6rs --program srfi-9-test.sps; echo
echo srfi-11-test; ${LARCENY} --r6rs --program srfi-11-test.sps; echo
echo srfi-13-test; ${LARCENY} --r6rs --program srfi-13-test.sps; echo
echo srfi-14-test; ${LARCENY} --r6rs --program srfi-14-test.sps; echo
echo srfi-16-test; ${LARCENY} --r6rs --program srfi-16-test.sps; echo
echo srfi-17-test; ${LARCENY} --r6rs --program srfi-17-test.sps; echo
echo srfi-19-test; ${LARCENY} --r6rs --program srfi-19-test.sps; echo
echo srfi-23-test; ${LARCENY} --r6rs --program srfi-23-test.sps; echo
echo srfi-25-test; ${LARCENY} --r6rs --program srfi-25-test.sps; echo
echo srfi-26-test; ${LARCENY} --r6rs --program srfi-26-test.sps; echo
echo srfi-27-test; ${LARCENY} --r6rs --program srfi-27-test.sps; echo
echo srfi-28-test; ${LARCENY} --r6rs --program srfi-28-test.sps; echo
echo srfi-29-test; ${LARCENY} --r6rs --program srfi-29-test.sps; echo
echo srfi-31-test; ${LARCENY} --r6rs --program srfi-31-test.sps; echo
echo srfi-38-test; ${LARCENY} --r6rs --program srfi-38-test.sps; echo
echo srfi-39-test; ${LARCENY} --r6rs --program srfi-39-test.sps; echo
echo srfi-41-test; ${LARCENY} --r6rs --program srfi-41-test.sps; echo
echo srfi-42-test; ${LARCENY} --r6rs --program srfi-42-test.sps; echo
echo srfi-43-test; ${LARCENY} --r6rs --program srfi-43-test.sps; echo
echo srfi-45-test; ${LARCENY} --r6rs --program srfi-45-test.sps; echo
echo srfi-48-test; ${LARCENY} --r6rs --program srfi-48-test.sps; echo
echo srfi-51-test; ${LARCENY} --r6rs --program srfi-51-test.sps; echo
echo srfi-54-test; ${LARCENY} --r6rs --program srfi-54-test.sps; echo
echo srfi-59-test; ${LARCENY} --r6rs --program srfi-59-test.sps; echo
echo srfi-60-test; ${LARCENY} --r6rs --program srfi-60-test.sps; echo
echo srfi-61-test; ${LARCENY} --r6rs --program srfi-61-test.sps; echo
echo srfi-63-test; ${LARCENY} --r6rs --program srfi-63-test.sps; echo
echo srfi-64-test; ${LARCENY} --r6rs --program srfi-64-test.sps; echo
echo srfi-66-test; ${LARCENY} --r6rs --program srfi-66-test.sps; echo
echo srfi-67-test; ${LARCENY} --r6rs --program srfi-67-test.sps; echo
echo srfi-69-test; ${LARCENY} --r6rs --program srfi-69-test.sps; echo
echo srfi-71-test; ${LARCENY} --r6rs --program srfi-71-test.sps; echo
echo srfi-74-test; ${LARCENY} --r6rs --program srfi-74-test.sps; echo
echo srfi-86-test; ${LARCENY} --r6rs --program srfi-86-test.sps; echo
echo srfi-87-test; ${LARCENY} --r6rs --program srfi-87-test.sps; echo
echo srfi-95-test; ${LARCENY} --r6rs --program srfi-95-test.sps; echo
echo srfi-98-test; ${LARCENY} --r6rs --program srfi-98-test.sps; echo
echo srfi-101-test; ${LARCENY} --r7rs --program srfi-101-test.sps; echo
echo srfi-78-test; ${LARCENY} --r6rs --program srfi-78-test.sps; echo
