(define fatal-error error)

(define FLOATabs abs)
(define FLOATsin sin)
(define FLOATcos cos)
(define FLOATatan atan)
(define FLOATsqrt sqrt)
(define FLOATmin min)
(define FLOATmax max)
(define FLOATround round)
(define FLOATinexact->exact inexact->exact)

(define bitwise-or fxlogior)
(define bitwise-and fxlogand)
(define bitwise-not fxlognot)
(define boyer-iters        10)
(define browse-iters      600)
(define conform-iters      20)
(define cpstak-iters      300)
(define ctak-iters         30)
(define dderiv-iters   800000)
(define deriv-iters    800000)
(define destruc-iters     300)
(define diviter-iters  400000)
(define divrec-iters   400000)
(define earley-iters      150)
(define fft-iters        2000)
(define fib-iters          50)
(define fibfp-iters        50)
(define maze-iters       2500)
(define mazefun-iters     100)
(define mbrot-iters        30)
(define nucleic-iters      10)
(define peval-iters       100)
(define pnpoly-iters    10000)
(define puzzle-iters      100)
(define ray-iters          10)
(define scheme-iters     3000)
(define simplex-iters   60000)
(define slatex-iters       20)
(define sum-iters       10000)
(define sumfp-iters     10000)
(define tak-iters        1000)
(define takl-iters        200)
(define trav1-iters        50)
(define trav2-iters        10)
(define triangl-iters      10)

(define smlboyer-iters     10)
(define nboyer-iters        3) ; problem size, not iterations
(define dynamic-iters      10)
(define graphs-iters       10)
(define lattice-iters       1)
(define nbody-iters         1)
(define quicksort-iters    10)
(define perm9-iters         5)
;;; CRASH - Test of crash condition.

(define (main . args)
  (run-benchmark
   "crash"
   1
   (lambda () (#f))
   (lambda (result)
     #t)))
(main)
