#!/bin/bash
# Copyright 1998 Lars T Hansen.
#
# $Id$
#
# Shell script to summarize CVS log entries.
#
# Usage: summarize-changes date
# where date is on form mm/dd/yy

if [ "$1" = "" ]; then
  echo "Usage: summarize-changes mm/dd/yy"
  exit 1
fi

cvs -q log -N -d ">$1" | \
 gawk 'BEGIN { clear=1; i=0; collect=0 } 
       /^RCS file:/ { if (clear) rcsfile=$3 }
       /^=====/     { if (i > 0) { 
                        print rcsfile; 
                        for ( x=0 ; x < i ; x++ ) print lines[x]
                        print "--------------------"
                      } 
                      clear=1; i=0; collect=0 }
       /^-----/     { collect=1; next }
       { if (collect) lines[i++] = $0 }'
