; Copyright 1998 Lars T Hansen.
;
; $Id$
;
; Macro expander interface for the interpreter and the top-level
; environment.  This file is loaded after Twobit's macro expander.

($$trace "macro-expand")

; Used by the interpreter.

(define (interpreter-macro-expand expr . rest)
  (let ((env (if (null? rest) 
                 (interaction-environment) 
                 (car rest))))
    (macro-expand expr (environment-syntax-environment env))))

; Exported to the user environment.

(define (toplevel-macro-expand expr . rest)
  (make-readable (apply interpreter-macro-expand expr rest)))

; `Twobit-sort' is used by Twobit's macro expander.

(define (twobit-sort less? list)
  (sort list less?))

; Generated by macro expander.

(define name:CAR '.car)
(define name:CDR '.cdr)
  
; eof

