/* DO NOT EDIT THIS FILE. Edit the config file and rerun "config". */

#define TIMER_EXCEPTION 0
#define TYPE_EXCEPTION 1
#define PROC_EXCEPTION 2
#define ARG_EXCEPTION 3
#define ARITH_EXCEPTION 4
#define UNDEF_EXCEPTION 5
